[book]
title = "My Book Title"
authors = ["Your Name"]
src = "1_chapters"

[output.html]

# mdbook-pandoc config for PDF
[output.pandoc.profile.pdf]
output-file = "book.pdf"  # inside book/pandoc/pdf/
to = "latex"
pdf-engine = "xelatex"
